In [1]:
import pandas as pd

df=pd.read_csv("car_data 8.csv")

print(df)

             Car_id        Date Customer Name  Gender  Annual Income  \
0      C_CND_000001    1/2/2022     Geraldine    Male          13500
1      C_CND_000002    1/2/2022           Gia    Male        1480000
2      C_CND_000003    1/2/2022        Gianna    Male        1035000
3      C_CND_000004    1/2/2022       Giselle    Male          13500
4      C_CND_000005    1/2/2022         Grace    Male        1465000
...             ...         ...           ...     ...            ...
23901  C_CND_023902  12/31/2023        Martin    Male          13500
23902  C_CND_023903  12/31/2023         Jimmy  Female         900000
23903  C_CND_023904  12/31/2023          Emma    Male         705000
23904  C_CND_023905  12/31/2023      Victoire    Male          13500
23905  C_CND_023906  12/31/2023       Donovan    Male        1225000

                               Dealer_Name    Company       Model  \
0      Buddy Storbeck's Diesel Service Inc       Ford  Expedition
1                         C & M Motors Inc      Dodge     Durango
2                              Capitol KIA   Cadillac    Eldorado
3                   Chrysler of Tri-Cities     Toyota      Celica
4                        Chrysler Plymouth      Acura          TL
...                                    ...        ...         ...
23901                     C & M Motors Inc   Plymouth     Voyager
23902       Ryder Truck Rental and Leasing  Chevrolet       Prizm
23903               Chrysler of Tri-Cities        BMW        328i
23904                    Chrysler Plymouth  Chevrolet       Metro
23905                      Pars Auto Sales      Lexus       ES300

                          Engine Transmission       Color  Price ($)  \
0      DoubleÂ Overhead Camshaft         Auto       Black      26000
1      DoubleÂ Overhead Camshaft         Auto       Black      19000
2              Overhead Camshaft       Manual         Red      31500
3              Overhead Camshaft       Manual  Pale White      14000
4      DoubleÂ Overhead Camshaft         Auto         Red      24500
...                          ...          ...         ...        ...
23901          Overhead Camshaft       Manual         Red      12000
23902  DoubleÂ Overhead Camshaft         Auto       Black      16000
23903          Overhead Camshaft       Manual         Red      21000
23904  DoubleÂ Overhead Camshaft         Auto       Black      31000
23905  DoubleÂ Overhead Camshaft         Auto  Pale White      27500

       Dealer_No  Body Style    Phone Dealer_Region
0      06457-3834        SUV  8264678    Middletown
1      60504-7114        SUV  6848189        Aurora
2      38701-8047  Passenger  7298798    Greenville
3      99301-3882        SUV  6257557         Pasco
4      53546-9427  Hatchback  7081483    Janesville
...           ...        ...      ...           ...
23901  60504-7114  Passenger  8583598         Pasco
23902  06457-3834    Hardtop  7914229    Middletown
23903  99301-3882      Sedan  7659127    Scottsdale
23904  53546-9427  Passenger  6030764        Austin
23905  38701-8047    Hardtop  7020564    Middletown

[23906 rows x 16 columns]

In [2]:
print(df.shape)

(23906, 16)

In [3]:
print(df.columns)

Index(['Car_id', 'Date', 'Customer Name', 'Gender', 'Annual Income',
       'Dealer_Name', 'Company', 'Model', 'Engine', 'Transmission', 'Color',
       'Price ($)', 'Dealer_No ', 'Body Style', 'Phone', 'Dealer_Region'],
      dtype='object')

In [4]:
print(df.head())

         Car_id      Date Customer Name Gender  Annual Income  \
0  C_CND_000001  1/2/2022     Geraldine   Male          13500
1  C_CND_000002  1/2/2022           Gia   Male        1480000
2  C_CND_000003  1/2/2022        Gianna   Male        1035000
3  C_CND_000004  1/2/2022       Giselle   Male          13500
4  C_CND_000005  1/2/2022         Grace   Male        1465000

                           Dealer_Name   Company       Model  \
0  Buddy Storbeck's Diesel Service Inc      Ford  Expedition
1                     C & M Motors Inc     Dodge     Durango
2                          Capitol KIA  Cadillac    Eldorado
3               Chrysler of Tri-Cities    Toyota      Celica
4                    Chrysler Plymouth     Acura          TL

                      Engine Transmission       Color  Price ($)  Dealer_No   \
0  DoubleÂ Overhead Camshaft         Auto       Black      26000  06457-3834
1  DoubleÂ Overhead Camshaft         Auto       Black      19000  60504-7114
2          Overhead Camshaft       Manual         Red      31500  38701-8047
3          Overhead Camshaft       Manual  Pale White      14000  99301-3882
4  DoubleÂ Overhead Camshaft         Auto         Red      24500  53546-9427

  Body Style    Phone Dealer_Region
0        SUV  8264678    Middletown
1        SUV  6848189        Aurora
2  Passenger  7298798    Greenville
3        SUV  6257557         Pasco
4  Hatchback  7081483    Janesville

In [5]:
print(df.tail())

             Car_id        Date Customer Name  Gender  Annual Income  \
23901  C_CND_023902  12/31/2023        Martin    Male          13500
23902  C_CND_023903  12/31/2023         Jimmy  Female         900000
23903  C_CND_023904  12/31/2023          Emma    Male         705000
23904  C_CND_023905  12/31/2023      Victoire    Male          13500
23905  C_CND_023906  12/31/2023       Donovan    Male        1225000

                          Dealer_Name    Company    Model  \
23901                C & M Motors Inc   Plymouth  Voyager
23902  Ryder Truck Rental and Leasing  Chevrolet    Prizm
23903          Chrysler of Tri-Cities        BMW     328i
23904               Chrysler Plymouth  Chevrolet    Metro
23905                 Pars Auto Sales      Lexus    ES300

                          Engine Transmission       Color  Price ($)  \
23901          Overhead Camshaft       Manual         Red      12000
23902  DoubleÂ Overhead Camshaft         Auto       Black      16000
23903          Overhead Camshaft       Manual         Red      21000
23904  DoubleÂ Overhead Camshaft         Auto       Black      31000
23905  DoubleÂ Overhead Camshaft         Auto  Pale White      27500

       Dealer_No  Body Style    Phone Dealer_Region
23901  60504-7114  Passenger  8583598         Pasco
23902  06457-3834    Hardtop  7914229    Middletown
23903  99301-3882      Sedan  7659127    Scottsdale
23904  53546-9427  Passenger  6030764        Austin
23905  38701-8047    Hardtop  7020564    Middletown

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_id         23906 non-null  object
 1   Date           23906 non-null  object
 2   Customer Name  23905 non-null  object
 3   Gender         23906 non-null  object
 4   Annual Income  23906 non-null  int64
 5   Dealer_Name    23906 non-null  object
 6   Company        23906 non-null  object
 7   Model          23906 non-null  object
 8   Engine         23906 non-null  object
 9   Transmission   23906 non-null  object
 10  Color          23906 non-null  object
 11  Price ($)      23906 non-null  int64
 12  Dealer_No      23906 non-null  object
 13  Body Style     23906 non-null  object
 14  Phone          23906 non-null  int64
 15  Dealer_Region  23906 non-null  object
dtypes: int64(3), object(13)
memory usage: 2.9+ MB

In [7]:
df.describe()

       Annual Income     Price ($)         Phone
count   2.390600e+04  23906.000000  2.390600e+04
mean    8.308403e+05  28090.247846  7.497741e+06
std     7.200064e+05  14788.687608  8.674920e+05
min     1.008000e+04   1200.000000  6.000101e+06
25%     3.860000e+05  18001.000000  6.746495e+06
50%     7.350000e+05  23000.000000  7.496198e+06
75%     1.175750e+06  34000.000000  8.248146e+06
max     1.120000e+07  85800.000000  8.999579e+06

In [8]:
df.describe(include="object")

,Car_id,Date,Customer Name,Gender,Dealer_Name,Company,Model,Engine,Transmission,Color,Dealer_No,Body Style,Dealer_Region
count,23906,23906,23905,23906,23906,23906,23906,23906,23906,23906,23906,23906,23906
unique,23906,612,3021,2,28,30,154,2,2,3,7,5,7
top,C_CND_000001,9/5/2023,Thomas,Male,Progressive Shippers Cooperative Association No,Chevrolet,Diamante,DoubleÂ Overhead Camshaft,Auto,Pale White,85257-3102,SUV,Austin
freq,1,190,92,18798,1318,1819,418,12571,12571,11256,3814,6374,4135

In [9]:
print(df['Car_id'])

0        C_CND_000001
1        C_CND_000002
2        C_CND_000003
3        C_CND_000004
4        C_CND_000005
             ...
23901    C_CND_023902
23902    C_CND_023903
23903    C_CND_023904
23904    C_CND_023905
23905    C_CND_023906
Name: Car_id, Length: 23906, dtype: object

In [10]:
print(df[['Customer Name','Gender','Dealer_Name']])

      Customer Name  Gender                          Dealer_Name
0         Geraldine    Male  Buddy Storbeck's Diesel Service Inc
1               Gia    Male                     C & M Motors Inc
2            Gianna    Male                          Capitol KIA
3           Giselle    Male               Chrysler of Tri-Cities
4             Grace    Male                    Chrysler Plymouth
...             ...     ...                                  ...
23901        Martin    Male                     C & M Motors Inc
23902         Jimmy  Female       Ryder Truck Rental and Leasing
23903          Emma    Male               Chrysler of Tri-Cities
23904      Victoire    Male                    Chrysler Plymouth
23905       Donovan    Male                      Pars Auto Sales

[23906 rows x 3 columns]

In [27]:
df_car=df[df['Price ($)']>20000]
print(df_car)

             Car_id        Date Customer Name Gender  Annual Income  \
0      C_CND_000001    1/2/2022     Geraldine   Male          13500
2      C_CND_000003    1/2/2022        Gianna   Male        1035000
4      C_CND_000005    1/2/2022         Grace   Male        1465000
7      C_CND_000008    1/2/2022        Graham   Male          13500
8      C_CND_000009    1/2/2022         Naomi   Male         815000
...             ...         ...           ...    ...            ...
23898  C_CND_023899  12/31/2023        Skylar   Male         530000
23899  C_CND_023900  12/31/2023          Yuna   Male          13500
23903  C_CND_023904  12/31/2023          Emma   Male         705000
23904  C_CND_023905  12/31/2023      Victoire   Male          13500
23905  C_CND_023906  12/31/2023       Donovan   Male        1225000

                               Dealer_Name     Company        Model  \
0      Buddy Storbeck's Diesel Service Inc        Ford   Expedition
2                              Capitol KIA    Cadillac     Eldorado
4                        Chrysler Plymouth       Acura           TL
7                                U-Haul CO  Mitsubishi       Galant
8                     Rabun Used Car Sales   Chevrolet       Malibu
...                                    ...         ...          ...
23898                 Rabun Used Car Sales       Volvo          C70
23899                            U-Haul CO       Buick  Park Avenue
23903               Chrysler of Tri-Cities         BMW         328i
23904                    Chrysler Plymouth   Chevrolet        Metro
23905                      Pars Auto Sales       Lexus        ES300

                          Engine Transmission       Color  Price ($)  \
0      DoubleÂ Overhead Camshaft         Auto       Black      26000
2              Overhead Camshaft       Manual         Red      31500
4      DoubleÂ Overhead Camshaft         Auto         Red      24500
7      DoubleÂ Overhead Camshaft         Auto  Pale White      42000
8              Overhead Camshaft       Manual  Pale White      82000
...                          ...          ...         ...        ...
23898          Overhead Camshaft       Manual  Pale White      24000
23899  DoubleÂ Overhead Camshaft         Auto  Pale White      62000
23903          Overhead Camshaft       Manual         Red      21000
23904  DoubleÂ Overhead Camshaft         Auto       Black      31000
23905  DoubleÂ Overhead Camshaft         Auto  Pale White      27500

       Dealer_No  Body Style    Phone Dealer_Region
0      06457-3834        SUV  8264678    Middletown
2      38701-8047  Passenger  7298798    Greenville
4      53546-9427  Hatchback  7081483    Janesville
7      78758-7841  Passenger  6206512        Austin
8      85257-3102    Hardtop  7194857         Pasco
...           ...        ...      ...           ...
23898  85257-3102  Hatchback  6225183         Pasco
23899  78758-7841  Hatchback  8384785        Aurora
23903  99301-3882      Sedan  7659127    Scottsdale
23904  53546-9427  Passenger  6030764        Austin
23905  38701-8047    Hardtop  7020564    Middletown

[15558 rows x 16 columns]

In [26]:
print(df['Transmission'].unique())

['Auto' 'Manual']